spring:
  datasource:
#    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/recuperation?serverTimezone=UTC}
#    &sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${JDBC_DATABASE_USERNAME:sa}
    password: ${JDBC_DATABASE_PASSWORD:password}
  dbcp2:
    max-wait-millis: 30000
    validation-query: "SELECT 1"
    validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
springdoc:
  pathsToMatch: /api/**
